# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
    'require':
      'frameworks/extra-cmake-modules': '@latest-kf6'
      'frameworks/ki18n': '@latest-kf6'
      'frameworks/kdbusaddons': '@latest-kf6'
      'frameworks/kcoreaddons': '@latest-kf6'
      'frameworks/kconfigwidgets': '@latest-kf6'
      'frameworks/kxmlgui': '@latest-kf6'
      'frameworks/kcrash': '@latest-kf6'
      'libraries/libqaccessibilityclient': '@latest-kf6'

  - 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
    'require':
      'frameworks/extra-cmake-modules': '@stable'
      'frameworks/ki18n': '@stable'
      'frameworks/kdbusaddons': '@stable'
      'frameworks/kcoreaddons': '@stable'
      'frameworks/kconfigwidgets': '@stable'
      'frameworks/kxmlgui': '@stable'
      'frameworks/kcrash': '@stable'
      'libraries/libqaccessibilityclient': '@latest-kf6'

Options:
  require-passing-tests-on: [ '@all' ]
