# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Accessibility Inspector"
SPDX-PackageSupplier = "Carl Schwan <carl@carlschwan.eu>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/accessibility/accessibility-inspector"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Carl Schwan <carl@carlschwan.eu>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "org.kde.accessibilityinspector.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "Uri Herrera <uri_herrera@nitrux.in> and others"
SPDX-License-Identifier = "LGPL-3.0-or-later"
